# Generated by Django 5.2.17 on 2026-10-04 13:59

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('total_start_time', models.FloatField()),
                ('total_end_time', models.FloatField()),
                ('total_area', models.FloatField()),
                ('selected_area', models.FloatField()),
                ('area_fraction_percent', models.FloatField()),
                ('point_count', models.PositiveIntegerField()),
                ('time_unit', models.CharField(max_length=12)),
                ('signal_unit', models.CharField(max_length=12)),
                ('area_unit', models.CharField(max_length=12)),
                ('fraction_unit', models.CharField(max_length=12)),
                ('source_sha256', models.CharField(max_length=64)),
                ('parser_version', models.CharField(max_length=64)),
                ('algorithm_version', models.CharField(max_length=64)),
                ('application_version', models.CharField(max_length=32)),
                ('git_commit', models.CharField(max_length=40, null=True)),
                ('working_tree_dirty', models.BooleanField()),
                ('runtime_versions', models.JSONField()),
                ('reason', models.TextField()),
                ('created_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='TraceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_bytes', models.BinaryField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_size', models.PositiveIntegerField()),
                ('points', models.JSONField()),
                ('point_count', models.PositiveIntegerField()),
                ('time_min', models.FloatField()),
                ('time_max', models.FloatField()),
                ('total_area', models.FloatField()),
                ('parser_version', models.CharField(max_length=64)),
                ('import_calculation_version', models.CharField(max_length=64)),
                ('import_build', models.JSONField()),
                ('imported_by_name', models.CharField(max_length=150)),
                ('imported_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed')], default='draft', max_length=12)),
                ('run_version', models.PositiveIntegerField(default=1)),
                ('reviewed_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('review_build', models.JSONField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trace_runs', to=settings.AUTH_USER_MODEL)),
                ('latest_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='review.analysisrevision')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='review.analysisrevision')),
            ],
            options={
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('trace_imported', 'trace_imported'), ('revision_saved', 'revision_saved'), ('review_completed', 'review_completed')], max_length=32)),
                ('actor_name', models.CharField(max_length=150)),
                ('occurred_at', models.DateTimeField()),
                ('version_before', models.PositiveIntegerField()),
                ('version_after', models.PositiveIntegerField()),
                ('context', models.JSONField()),
                ('request_id', models.UUIDField(unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='review.analysisrevision')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='review.tracerun')),
            ],
            options={
                'ordering': ['version_after'],
            },
        ),
        migrations.AddField(
            model_name='analysisrevision',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='review.tracerun'),
        ),
        migrations.AddConstraint(
            model_name='tracerun',
            constraint=models.CheckConstraint(condition=models.Q(('run_version__gte', 1)), name='run_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='tracerun',
            constraint=models.CheckConstraint(condition=models.Q(('point_count__gte', 2), ('point_count__lte', 2000)), name='run_point_count'),
        ),
        migrations.AddConstraint(
            model_name='tracerun',
            constraint=models.CheckConstraint(condition=models.Q(('source_size__lte', 262144)), name='run_source_size'),
        ),
        migrations.AddConstraint(
            model_name='tracerun',
            constraint=models.CheckConstraint(condition=models.Q(('time_min__lt', models.F('time_max')), ('total_area__gt', 0)), name='run_positive_window'),
        ),
        migrations.AddConstraint(
            model_name='tracerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('review_build__isnull', True), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('reviewed_revision__isnull', True), ('status', 'draft')), models.Q(('latest_revision', models.F('reviewed_revision')), ('review_build__isnull', False), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('reviewed_revision__isnull', False), ('status', 'reviewed')), _connector='OR'), name='run_completion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('run', 'version_after'), name='unique_run_event_version'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('version_after', django.db.models.expressions.CombinedExpression(models.F('version_before'), '+', models.Value(1)))), name='event_next_version'),
        ),
        migrations.AddConstraint(
            model_name='analysisrevision',
            constraint=models.UniqueConstraint(fields=('run', 'revision_number'), name='unique_run_revision'),
        ),
        migrations.AddConstraint(
            model_name='analysisrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='revision_positive_number'),
        ),
        migrations.AddConstraint(
            model_name='analysisrevision',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__lte', models.F('total_end_time')), ('start_time__gte', models.F('total_start_time')), ('start_time__lt', models.F('end_time'))), name='revision_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='analysisrevision',
            constraint=models.CheckConstraint(condition=models.Q(('area_fraction_percent__gte', 0), ('area_fraction_percent__lte', 100), ('selected_area__gte', 0), ('selected_area__lte', models.F('total_area')), ('total_area__gt', 0)), name='revision_valid_result'),
        ),
        migrations.AddConstraint(
            model_name='analysisrevision',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='revision_reason_required'),
        ),
    ]
